version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=US/Central
      - PORT=5055 #optional
    network_mode: "host"
    ports:
      - 5055:5055
    volumes:
      - overseerr-data:/app/config
    restart: unless-stopped

volumes:
  overseerr-data:
    external: true