version: '2'
services:
  readarr:
    container_name: readarr
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./readarr.dockerfile
    network_mode: "host"
    user: readarr
    volumes:
      - /netstorage/books:/books
      - /netstorage/downloads:/downloads
      - readarr-data:/config

volumes:
  readarr-data:
    external: true