version: '2'
services:
  prowlarr:
    container_name: prowlarr
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./prowlarr.dockerfile
    network_mode: "host"
    user: prowlarr
    volumes:
      - prowlarr-data:/config

volumes:
  prowlarr-data:
    external: true