version: '2'
services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./radarr.dockerfile
    ports:
      - "7878:7878"
    network_mode: "host"
    user: radarr
    volumes:
      - /netstorage/movies:/movies
      - /netstorage/downloads:/downloads
      - radarr-data:/config

volumes:
  radarr-data:
    external: true